"""followers

Revision ID: 522c83a8655c
Revises: 1bb0caa43c89
Create Date: 2023-06-16 23:54:34.249075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522c83a8655c'
down_revision = '1bb0caa43c89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
